name: Pull Request Previews

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - "packages/**"
      - "examples/fineFoods/**"

jobs:
  antd-fine-foods:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm ci
          npm run bootstrap -- --scope fine-foods
          npm run build -- --scope fine-foods
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.PANKOD_BOT_TOKEN }}
          dist: examples/fineFoods/admin/antd/build
          teardown: 'true'
          build: echo
  mui-fine-foods:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm ci
          npm run bootstrap -- --scope mui-fine-foods
          npm run build -- --scope mui-fine-foods
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.PANKOD_BOT_TOKEN }}
          dist: examples/fineFoods/admin/mui/build
          teardown: 'true'
          build: echo